// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADFmUJw5Kz4RNemzHb17sckZX-cNyRXgA',
    appId: '1:933062366054:web:10f8d9f279f722f1ac2ea7',
    messagingSenderId: '933062366054',
    projectId: 'brewapp-task',
    authDomain: 'brewapp-task.firebaseapp.com',
    storageBucket: 'brewapp-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz7nhYwtNsl3SSU2NAxz4NycyXsYqGYkc',
    appId: '1:933062366054:android:87a812f42ef010a2ac2ea7',
    messagingSenderId: '933062366054',
    projectId: 'brewapp-task',
    storageBucket: 'brewapp-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoO5uBJxNk0gmxSzx9bIqIuMIz0gxOVP8',
    appId: '1:933062366054:ios:91bfcc41f80a9e39ac2ea7',
    messagingSenderId: '933062366054',
    projectId: 'brewapp-task',
    storageBucket: 'brewapp-task.appspot.com',
    iosClientId: '933062366054-0g3cctv4l79aaoe851i517ntoh572btl.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewappTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoO5uBJxNk0gmxSzx9bIqIuMIz0gxOVP8',
    appId: '1:933062366054:ios:91bfcc41f80a9e39ac2ea7',
    messagingSenderId: '933062366054',
    projectId: 'brewapp-task',
    storageBucket: 'brewapp-task.appspot.com',
    iosClientId: '933062366054-0g3cctv4l79aaoe851i517ntoh572btl.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewappTask',
  );
}
